[package]
name = "observer-app-mock"
version = "0.1.0"
edition = "2021"

[dependencies]
observer-common = { path = "../observer-common" }

[features]
observer-mock = ["observer-common/observer-mock"]

[[bin]]
name = "observer-app-mock"
path = "src/main.rs"
required-features = ["observer-mock"]
