# SPDX-License-Identifier: Apache-2.0

name: Rust

on:
  push:
    branches: [ main ]
    paths:
      - 'components/rust/**'
      - 'components/solidity/artifacts/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'components/rust/**'
      - 'components/solidity/artifacts/**'

jobs:
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/checkout@v4
      - name: Build Rust Components
        run: make -C components/rust
