# SPDX-License-Identifier: Apache-2.0

name: Solidity

on:
  push:
    branches: [ main ]
    paths:
      - 'components/solidity/**'
      - 'pnpm-*.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'components/solidity/**'
      - 'pnpm-*.yaml'

jobs:
  build-solidity:
    runs-on: ubuntu-latest

    services:
      sapphire-localnet-ci:
        image: ghcr.io/oasisprotocol/sapphire-localnet:latest
        ports:
          - 8545:8545
          - 8546:8546
        env:
          OASIS_DOCKER_START_EXPLORER: no
        options: >-
          --rm
          --health-cmd="test -f /CONTAINER_READY"
          --health-start-period=90s

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build & Test
        run: make -C components/solidity

      - name: Build & Test (sapphire-localnet)
        run: make -C components/solidity test-localnet
